### PR TITLE
Fix pangram README to state that some test input will include non-ASCII input

### PR DESCRIPTION
**Pull request by liammccartney**
The test suite for the pangram exercise [includes a test with non-ASCII input.](https://github.com/exercism/elm/blob/master/exercises/pangram/tests/Tests.elm#L56-L60)
However, the README states that no input will contain non-ASCII characters. 
This PR changes the README to state that some input will contain non-ASCII characters.

### CODE REVIEW

**Comment by tuxagon** [comment]
Thanks for the PR, @liammccartney. Sorry it has taken so long to respond. 

I'm wondering if changing the README or removing the test is the better option. @kytrinyx, is there an exercism preference here? I did notice in the [elixir](https://github.com/exercism/elixir/blob/bcaae351486b1405f0a01cd33b4d39555546298e/exercises/pangram/pangram_test.exs#L53) track that there are 2 non-ASCII tests. This might be a bigger change that should trickle down to each track. Thoughts?

**Comment by neganp** [comment]
Because the difficulty of handling non-ASCII text varies dramatically between languages, I don't think putting it in every language makes sense. Based on the example implementation, it looks like it's not too much trouble to do it in Elm, so I think updating the README is adequate.

**Comment by kytrinyx** [comment]
The Exercism preference is to get the test suite the way you like it for this particular language, and then tweak the README to match.

The exercise READMEs are generated using Configlet (the command-line tool we use for various track-configuration things).

The TL;DR is you'll want to copy the `description.md` from the exercise in the [problem-specifications](http://github.com/exercism/problem-specifications) repository, and stick it in `exercises/pangram/.meta/description.md` and then edit the one in this repo, then regenerate with `configlet generate . --only=pangram --spec-path=../path/to/problem-specifications`.

The longer docs are at https://github.com/exercism/docs/blob/master/maintaining-a-track/regenerating-exercise-readmes.md and https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/readmes.md

**Comment by neganp** [comment]
Thanks for the info :+1:!

@liammccartney, I think I've got an update that will make your fix permanent [here](https://github.com/neganp/elm/commit/5c37e4ca6487ca98ddf714246255b80f2e50b3c0). Do you want to cherry pick that commit to your branch and re-submit the PR? Or I could try to send the change to your branch?

**Comment by liammccartney** [comment]
Hi @neganp - apologies for the delayed response! Github notifications are easily lost.

I'll re-submit the PR with that commit cherry-picked later tonight. Thanks!

**Comment by liammccartney** [comment]
@neganp cherry-picked and pushed! Thanks!

**Comment by neganp** [comment]
Awesome :+1: Thanks for the fix!

**Comment by liammccartney** [comment]
Thanks everyone! This was my first OSS contribution 🎉

**Comment by tuxagon** [comment]
Thanks, @liammccartney, for the contribution!

**Pull request merged**
