### PR TITLE
Add version test to triangle exercise

### PR DESCRIPTION
**Pull request by iamvery**
This follows the pattern set by some of the other exercises. I noticed it was missing from the triangle exercise.

### CODE REVIEW

**Comment by tgecho** [comment]
Good catch! Looks like you forgot to expose `Triangle.version` :)

**Comment by iamvery** [comment]
Whoops! 😂  Fixed 💫

**Comment by iamvery** [comment]
Curious, would it be preferable to access the function with the fully-qualified name `Triangle.version` rather than have it exposed to the `Tests` module? My thinking is that `version` is an awful generic name for a function. Perhaps I'm overthinking it here, but still interesting to me in general if that's a consideration...

**Comment by tgecho** [comment]
A fair question. In general, I'm coming to prefer using qualified names more and more. This case is simple/static enough that I don't think it's worth any more effort :)

**Pull request merged**
