### PR TITLE
Add Cedd Burge as a maintainer

### PR DESCRIPTION
**Pull request by ceddlyburge**
As requested on slack

### CODE REVIEW

**Comment by mpizenberg** [comment]
I think you've done quite a lot already for the track with the research experiment so I don't mind setting `show_on_website` to `true` directly. I think the advise to set is to `false` was mostly for completely new maintainers responding to the call.

**Comment by ceddlyburge** [comment]
Thanks Matthieu, I've updated this.

**Comment by mpizenberg** [comment]
Hi Cedd, just to let you know I've seen and will merge but there are few configuration changes being tested by exercism team now. I'm waiting to be able to merge without squashing or rebasing.

**Comment by ceddlyburge** [comment]
No problem Matthieu, thanks for letting me know

**Comment by mpizenberg** [comment]
I'm actually going to squash and merge, just out of curiosity to see how it behaves in this case (2 commits). I'm interested to see how the commits are referenced in this discussion afterward.

**Pull request merged**
