### PR TITLE
Add resistor color trio exercise

### PR DESCRIPTION
**Pull request by leojpod**
Following up on the other exercise, let's add a simpler one :)

### CODE REVIEW

**Comment by mpizenberg** [comment]
Thank you @leojpod ! I wanted to give some feedback on this and propose an alternative implementation with dicts for colors, but having to switch to 0.19.0 to get the build tests compile is a bit annoying.

I've started the process to upgrade this track to elm 0.19.1 and laid out the things to do in issue #278. I'd like to prioritize the upgrade, and so any help on this is welcomed. I'll be able to come back to this and your other PRs after the upgrade is done.

**Comment by leojpod** [comment]
- [ ] Rebase on master: git rebase origin/master if you've configured origin to be exercism/elm repository
- [ ] Seems like you don't have formatting issues for config.json in those PRs so nothing to do here
- [ ] Move implementations to the src/ dir to adapt to elm 0.19.1
- [ ] Use template/elm.json for the elm.json file
- [ ] Update exercise readme with new template with bin/configlet generate . --only <exercise-slug>

**Comment by mpizenberg** [comment]
What do you think of something like the following? I feel that using custom types is better to show new elm developers that we should reach for the type that provides most compilation guaranties if possible.

```elm
type Color
    = Black
    | ...
    | White

colorValue : Color -> Int
colorValue color =
    case color of
        Black -> 0
        ...
        White -> 9

colorsToOhms : Color -> Color -> Color -> String
colorsToOhms a b c =
    formatOhms (tricolorValue a b c)

tricolorValue : Color -> Color -> Color -> Int
tricolorValue a b c =
    (10 * colorValue a + colorValue b) * (10 ^ colorValue c)

formatOhms : Int -> String
formatOhms ohms =
    ...
```

**Comment by leojpod** [comment]
I had done this at first and then thought that there wasn't actually much more garranties that way: you'll need to parse the colors into value one way or another :) 

but I think your point. we could change it to use union types 👍  I'll try to get that done soon enough

**Comment by leojpod** [comment]
ping to myself (@leojpod) so I hopefully remember to get that done!

**Comment by ceddlyburge** [comment]
Hi @leojpod! This PR is quite old now, and may or may not make sense now that we have moved to exercism v3.

Are you still planning to finish the exercise? If not I'll close the pull request.

If you are keen to get involved there are plenty of concepts / concept exercises to write for v3 at the momet :)

The issues have all the details.

Please let me know if you have any questions.

Thanks, Cedd

**Comment by leojpod** [comment]
Hi @ceddlyburge ! 

Sorry, I don't have much time to work on this nowadays. 
I guess we can close it, the elm part of the exercise will still be out-there if needed one day :D 

I'll have a look at the concept stuff if I get a minute :) 

Sorry for dropping the ball on that one..

**Comment by ceddlyburge** [comment]
No worries, I think balls were dropped all round! We can keep the branch in case someone wants to come back to it later.

**Pull request closed without merging**
