### PR TITLE
Turn on analyzer

### PR DESCRIPTION
**Pull request by jiegillet**
After this, the analyzer should be live 🎉

### CODE REVIEW

**Comment by jiegillet** [comment]
I stand corrected, it's live already!
Screen Shot 2022-03-08 at 18 42 59

**Review by ErikSchierboom — APPROVED** [review]
Ah well, that must be a bug then! But great to see it working

**Comment by jiegillet** [comment]
Thanks for your help! 
I'm very happy to see it live :)

**Comment by ErikSchierboom** [comment]
Indeed! Very cool

**Comment by mpizenberg** [comment]
Just tested it too, amazing! Thank you very much @jiegillet for making this and @ceddlyburge @ErikSchierboom for reviewing!

**Pull request merged**
