### PR TITLE
Update concept contrib doc to foster new contributions

### PR DESCRIPTION
**Pull request by mpizenberg**

### CODE REVIEW

**Comment by mpizenberg** [comment]
The image included is the following
image

**Comment by mpizenberg** [comment]
I've also added many issues in the issue tracker with basically the content of their `design.md` in the issue, or a good base for it. I've marked them with the relevant exercism labels. This way they appear on the task explorer of the website https://exercism.org/contributing/tasks?track_slug=elm&order=newest

**Comment by ceddlyburge** [comment]
Hi Matthieu, do you want me to review this?
Cheers, Cedd

**Comment by mpizenberg** [comment]
Indeed, it seems I forgot to ping you here

**Review by ceddlyburge — APPROVED** [review]
Looks good, the issues are especially helpful

**Pull request merged**
