### PR TITLE
Update links to bekk.christmas blog

### PR DESCRIPTION
**Pull request by ceddlyburge**
The old blog has had its name changed, but the content is the same

### CODE REVIEW

**Comment by ceddlyburge** [comment]
Hi @exercism/reviewers, Matthieu is super busy, and its only me and him maintaining the Elm track at the moment, so there isn't anybody to review / approve my pull requests at the moment. I emailed the only other maintainer, but he has been inactive for years, and didn't reply.
Could somebody take a look?
Thanks, Cedd

**Review by BethanyG — APPROVED** [review]
Looks good!

**Comment by BethanyG** [comment]
@ceddlyburge  - I am on the `exercism/reviewers` team,  but it looks like they haven't been added to this repo.  I think you may need to ping @ErikSchierboom  or another admin to discuss.

**Comment by ceddlyburge** [comment]
Thanks @BethanyG , I think he will get. your notification, so let's see what happens! Cheers, Cedd

**Review by ErikSchierboom — APPROVED** [review]

**Pull request merged**
