### PR TITLE
Add binary search exercise

### PR DESCRIPTION
**Pull request by churchie317**

### CODE REVIEW

**Comment by churchie317** [comment]
FYI: the documentation is confusing with respect to inclusion of a README.md. Specifically the documentation says:

> Please do not add a README or README.md file to the exercise directory. The READMEs are constructed using shared metadata, which lives in the exercism/problem-specifications repository.

However, when I submitted the work without a README.md, the CI/CD pipeline failed.

**Comment by neganp** [comment]
Nice! Thanks so much for porting this exercise, and thanks for flagging the README issue. I think there README situation is a work in progress, but this work can be merged as soon as it's sorted out. 👍

Sorry for the delay. 😞

**Comment by neganp** [comment]
Woah, this PR is getting kind of huge. It looks like maybe commits from other branches are being included? Would it be possible to cherry-pick the binary search commits onto a clean branch? I can take a stab at it if you don't mind (I don't want to steal anyone's thunder, just trying to keep things organized).

**Comment by tuxagon** [comment]
@churchie317 This will probably need an update due to #198. It was hard to tell due to whatever happened to the commit history here. All that would entail is removing `package.json` (and `package-lock.json` if it exists) from the exercise directory.

**Comment by churchie317** [comment]
Yep! I'll work on this tonight or tomorrow to pick the relevant commits.

**Comment by tuxagon** [comment]
@churchie317 Also, I would recommend waiting for #198 to merge so that you can regenerate your README to take the updates. Lots 'o changes :sweat_smile: I'm waiting for #170 as well because it'll be easier.

**Comment by churchie317** [comment]
Closing because this somehow snuck its way in and @tuxagon made it consistent with other exercises in #198. 

[Proof](https://github.com/exercism/elm/pull/198/files#diff-012e819d64b3de0dcabfaf97752beedb)

**Comment by tuxagon** [comment]
I'm not sure how that happened :confused: Something weird happened with the history here. Nbd, I guess :sweat_smile:

**Comment by churchie317** [comment]
Yeah, pretty sure I did something derpy. My bad 🙇 y'all.

**Comment by tuxagon** [comment]
No worries. If something is wrong, we can open a PR later.

**Pull request closed without merging**
