### PR TITLE
Upgrade 0.19

### LINKED ISSUE #229: Upgrade to 0.19
Since 0.19 came out, we should update this track to use the latest and greatest elm

### PR DESCRIPTION
**Pull request by tuxagon**
Fixes #229 🎉 

This is a large pull request and I've attempted to make the commits easier to follow.

The breakdown goes as such
1. Meta updates for the repository and exercism itself
2. Update all the exercises to be 0.19 compatible
3. Finishing touches

I plan to merge this in a couple weeks unless something comes up or something needs fixed and it takes longer. I want to give time to anyone reviewing; however, since this is SO big, I don't want to hinder being able to use 0.19 because it doesn't get a very intricate review by someone in their free time.

Please comment if you have anything to say

### CODE REVIEW

**Comment by neganp** [comment]
Congrats on getting this ready, and thank you **so much** for all your hard work! This is tremendous. :+1:

**Comment by tuxagon** [comment]
It feels good to finally get that little green checkmark 😅

**Comment by tuxagon** [comment]
I should also mention that for each exercise, the commit contains a little upgrade changelog to help see what changed. It was mainly to give a quick description of why those changes were made. I tried to make minimal changes.

**Comment by tuxagon** [comment]
As an FYI, I plan to merge this on 10/10 unless someone has comments.

**Comment by tuxagon** [comment]
@N-Parsons Updated documentation in commit https://github.com/exercism/elm/pull/230/commits/56f01642cdfdced6db8b9a0e77b60d046476a1f7

**Comment by N-Parsons** [comment]
@tuxagon, the changes to the README template look good, but don't forget to run the configlet to regenerate all of the READMEs!

**Comment by tuxagon** [comment]
@N-Parsons yep. I meant to do that. Done now.

**Pull request merged**
