### PR TITLE
Add "wordy" exercise

### PR DESCRIPTION
**Pull request by SiriusStarr**
Per #289 .

### CODE REVIEW

**Comment by mpizenberg** [comment]
The `Hints` section I think would be a good idea but I think we have to not change the generated readme, and I'm not aware of a mechanism to have a personalized section for a common exercise. Would you mind asking about this on the exercism slack?

**Comment by SiriusStarr** [comment]
@mpizenberg  You can!  I just was half asleep and forgot to stage the `hints.md` file, haha.  [Here's the info on how to do it.](https://github.com/exercism/website-copy/blob/master/pages/become_a_maintainer.md#adding-hints)

**Comment by mpizenberg** [comment]
> @mpizenberg You can! I just was half asleep and forgot to stage the hints.md file, haha. Here's the info on how to do it.

Oh nice, I didn't know about this one!

Regarding the implementation, I'm wondering why the `Number` type is needed. Wouldn't it be simpler to hold operations like these?

```elm
type Operation = Add Int | Multiply Int | Divide Int
```

We could have

```elm
parser : Parser (Int, List Operation)
solveProblem : (Int, List Operation) -> Int
```

I feel like it would simplify the code but not sure, I haven't done it. What do you think?

**Comment by SiriusStarr** [comment]
Undoubtedly, I just copy-pasted my (admittedly crappy) Haskell solution, haha.  I will clean it up in a bit.

**Comment by SiriusStarr** [comment]
Okay, updated with an even simpler solution.  Now off to fix my Haskell solution, haha.  :eyes:

**Comment by mpizenberg** [comment]
Looks good!

**Pull request merged**
