### PR TITLE
Add bowling exercise

### PR DESCRIPTION
**Pull request by leojpod**
Implementation of the [bowling exercise](https://github.com/exercism/problem-specifications/tree/master/exercises/bowling)

### CODE REVIEW

**Comment by ceddlyburge** [comment]
Hi @leojpod! 

I see we have been ignoring another one of your pull requests. apologies. Please let me know if you would still like to merge this and I will take a look.

Thanks, Cedd

**Comment by leojpod** [comment]
Hi @ceddlyburge 

oh that one doesn't have conflicts! 
well why not :) 
at least let's see how many things need to be adjusted/changed for it to fit in V3 :)

**Comment by ceddlyburge** [comment]
Hi Hi @leojpod, are you happy if I make some changes to this PR and then get back to you? Some of the copy / text needs to be a bit different for v3 and things like that.
Cheers, Cedd

**Comment by leojpod** [comment]
Yes no problems at all :)

**Pull request closed without merging**
