### PR TITLE
Consistency

### PR DESCRIPTION
**Pull request by tuxagon**
This takes care of #194 and #182. The gist of the changes include
* Removing exercise specific `package.json` files
* ~Updated `bin/build.sh` to use `elm-test` explicitly~
* Changed installation instructions to favor a global install
* Updated template and regenerated all READMEs

Outstanding questions include
* What are your thoughts on the new installation instructions since they needed to be updated to reflect `elm-test` too.
* Do you see anything I missed?

### CODE REVIEW

**Comment by neganp** [comment]
Nice! :clap: 

Nothing jumps out at me after a brief review.

If I had to nitpick, I'd say this PR might be improved by splitting it up (e.g: update docs, update package.json, then update the exercises), but I don't think it's a problem in this case.

Thanks for taking care of all these. :+1:

**Comment by tuxagon** [comment]
@neganp I thought about that, but I didn't think it would be a good idea to have it be in a non-consistent state while separating the logical pieces. I instead went for very granular focused commits instead.

Thoughts?

**Comment by neganp** [comment]
I think that makes sense. :slightly_smiling_face: 

Would you be okay leaving this open over the weekend to give folks a chance to comment and merging it on Monday if nothing comes up?

**Comment by tuxagon** [comment]
I'm fine with that because I also want to update #170 to follow this. Do you want to merge it or me?

**Comment by neganp** [comment]
Whoever gets to it first :+1:

**Comment by tuxagon** [comment]
The race is on 😉

**Pull request merged**
