### PR TITLE
Added CollatzConjecture

### PR DESCRIPTION
**Pull request by mortenaa**
Hey, I had a go at adding the Collatz Conjecture exercise. Wasn't sure if I should add it to config.json also

### CODE REVIEW

**Comment by tgecho** [comment]
Hey, looks good at first glance!

You will need to add it to the config to get the CI passing. Also, it looks like something may need to get run through elm-format while you at it: https://travis-ci.org/exercism/elm/jobs/284725128

**Comment by mortenaa** [comment]
@tgecho What should the uuid for an exercise in config.json be?

**Comment by anuragsoni** [comment]
@mortenaa there is a file called https://github.com/exercism/elm/blob/master/bin/fetch-configlet

if you run that you can generate the uuid using ./bin/configlet uuid

**Comment by mortenaa** [comment]
The various scripts in ./bin doesn't work to well on windows (using mingw bash) had to download configlet and elm-format manually.

**Comment by anuragsoni** [comment]
@mortenaa could you describe the errors? I don't have a windows machine to test it but I'm sure someone else would be able to help and/or update the scripts.

**Comment by mortenaa** [comment]
Well, first running ./bin/build.sh results in `./bin/build.sh: line 13: bin/elm-format: cannot execute binary file: Exec format` because the elm-format in bin is a linux executable.

trying to run the install-elm-format script only downloads the linux executable again, because `uname` returns `MINGW64_NT-6.1` which doesnt match any of the cases in the script.

changing the case statement to include `mingw` doesn't work as it still tries to download with extension tgz while the windows file has extension zip.

To conclude, I don't see how this can ever have worked on windows :-)

I can try to fix the scripts to work for me a little later if I have time :-)

**Comment by mortenaa** [comment]
@anuragsoni Hey, the changes I had to do to make the build script work for me are in pull request #163

**Comment by anuragsoni** [comment]
@mortenaa I left a comment on #163 about the line endings. But I believe this PR should still be a candidate for merging

**Comment by tgecho** [comment]
Thanks for your patience (and your help, @anuragsoni). Everything looks good now!

**Comment by anuragsoni** [comment]
@tgecho you are welcome 😄

**Pull request merged**
