### PR TITLE
rotational-cipher

### PR DESCRIPTION
**Pull request by anuragsoni**
This is my initial attempt to port my solution in elixir (https://github.com/anuragsoni/exercism/tree/master/elixir/rotational-cipher)

I'd like to get some feedback on the style and discuss if there could be another approach that will be more clear

### CODE REVIEW

**Comment by anuragsoni** [comment]
@tgecho this is ready for review

**Comment by tuxagon** [comment]
@anuragsoni We apologize for letting this get stale. Are you still interested in this getting reviewed?

**Comment by anuragsoni** [comment]
@tuxagon yes I am.

**Comment by yurrriq** [comment]
At first glance, this looks like it needs some reformatting. See also: https://github.com/exercism/elm/pull/178

**Comment by tuxagon** [comment]
@anuragsoni Once you resolve the conflicts with this branch, I can review and get this PR going forward. I'm really sorry for the delays; some changes happened to repo and we were prioritizing some of those, but they are done right now.

**Comment by anuragsoni** [comment]
@tuxagon I don't have Elm setup on my computer anymore, but i'll try to fix the conflicts/refresh this PR this weekend.

**Comment by tuxagon** [comment]
@anuragsoni Sounds good. If you have any issues, let me know. As a quick checklist for you, the things that will have changed will require

- [ ] Use `bin/install-elm-format && bin/elm-format exercises/rotational-cipher --yes` to format your elm code to pass tests
- [ ] Remove `package.json` and `package-lock.json` from `exercises/rotational-cipher`, if they exist
- [ ] Use `bin/fetch-configlet && configlet generate .` to generate `README.md`

I hope that helps you when revisiting this exercise.

**Pull request closed without merging**
