### PR TITLE
Check that all concept exercise tests have a task ID

### PR DESCRIPTION
**Pull request by jiegillet**
Closes https://github.com/exercism/elm-test-runner/issues/50

As a test, I added a commit that should fail the CI ([63fd952](https://github.com/exercism/elm/pull/625/commits/63fd9529956b913a40930c5151aeff4e5c4e888d)), and once reverted ([5bc194e](https://github.com/exercism/elm/pull/625/commits/5bc194e41f3fb848712428e72c08f586c7edfbb4)) it should pass.

### CODE REVIEW

**Comment by jiegillet** [comment]
As expected the [CI failed](https://github.com/exercism/elm/actions/runs/6674882425/job/18142257723?pr=625) with the message
```
Running tests for concept exercise /tmp/exercices_XXXXgpjBbB/concept/maze-maker
tinyproxy: Could not create listening sockets.
At least one test in /tmp/exercices_XXXXgpjBbB/concept/maze-maker is missing a task id (defined with 'describe "1"')
```
I will now revert the change.

**Comment by jiegillet** [comment]
CI passes ✅

**Review by mpizenberg — APPROVED** [review]
Alright, it's better to have the check than not have it. LGTM.

**Comment by jiegillet** [comment]
If we ever have a compelling case for having tests outside of tasks, let's absolutely revisit this check.

**Pull request merged**
