### PR TITLE
Implemented twelve-days exercise

### PR DESCRIPTION
**Pull request by tuxagon**
I went ahead and implemented the `twelve-days` exercise. Let me know what I need to do to get it accepted.

### CODE REVIEW

**Comment by tuxagon** [comment]
Is anyone doing anything in this repository?

**Comment by neganp** [comment]
I don't know, but I sure hope so 🙏

**Comment by neganp** [comment]
The code and explanation here look good, thanks for writing them!

I'm not sure how this interacts with #187, so I think we should hold off on merging until that's finished.

**Comment by tuxagon** [comment]
@neganp I agree

**Comment by churchie317** [comment]
Amazing 👏 👏 👏 !

One small tweak when this does get merged in: looks like the package-lock.json was included in the commit. For consistency's sake we should probably remove that.

**Comment by tuxagon** [comment]
@churchie317 May I ask why `package-lock.json` be removed? It was added in a more recent version of npm to lock the full dependency tree, so that you can have more control over nested dependencies. It's a trackable file that any modern app running on node is bound to have.

**Comment by churchie317** [comment]
Ah, my apologies. I've been out of the Node ecosystem for some time. If that's the case should we begin making it a requirement for all exercise submissions?

**Comment by tuxagon** [comment]
@churchie317 It would probably be a good idea to check for it; however, I just looked at the existing exercises and we have a lot of inconsistency. 

I will create an issue detailing the inconsistencies and that issue can reconcile the consistency problem.

**Comment by tuxagon** [comment]
Create #194

**Comment by tuxagon** [comment]
I still need to remove the `package.json` for this to agree with #198.

**Comment by tuxagon** [comment]
@neganp is this good to merge?

**Comment by neganp** [comment]
This looks great! :+1: Since this has been open so long, I'll go ahead and merge it. On the off-chance that someone takes issue, we can revert it or edit it once it's in.

Thanks again for all your work on this exercise! :100:

**Pull request merged**
