### PR TITLE
Add test case for Gotta Snatch'Em All

### PR DESCRIPTION
**Pull request by nico-or**
Add a test case for totalCards using a singleton list as input since there it wasn't any before.

Discussed in issue #684

### CODE REVIEW

**Comment by nico-or** [comment]
I wasn't aware of the [no important files changed] flag. Should I add it to the commit body to avoid the re-run of tests?

**Comment by jiegillet** [comment]
> I wasn't aware of the [no important files changed] flag. Should I add it to the commit body to avoid the re-run of tests?

No don't, this new test could potentially reveal issues with some solutions, rerunning the tests is what we want :)

**Comment by jiegillet** [comment]
@nico-or any reason why this is still a draft?

**Comment by nico-or** [comment]
> @nico-or any reason why this is still a draft?

No, I just forgot to switch the status.

**Review by jiegillet — APPROVED** [review]
Thank you 👍

**Pull request merged**
